const CartActionTypes = {
  TOGGLE_CART_START: "TOGGLE_CART_START",
  TOGGLE_CART_SUCCESS: "TOGGLE_CART_SUCCESS",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
};

export default CartActionTypes;
